# Generated by Django 2.0.3 on 2018-03-18 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chirp',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='chirp',
            name='content3',
        ),
    ]
