# Generated by Django 2.0.3 on 2018-03-18 23:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0002_auto_20180318_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chirp',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chirp',
            name='content',
            field=models.CharField(max_length=140),
        ),
    ]
