# Generated by Django 2.0.3 on 2018-03-19 00:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chirps', '0003_auto_20180318_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='user',
            field=models.ForeignKey(default=1, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
