# Generated by Django 2.0.3 on 2018-03-19 02:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0004_chirp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='user',
            field=models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
