# Generated by Django 2.0.3 on 2018-03-19 02:10

import chirps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0005_auto_20180318_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='content',
            field=models.CharField(max_length=140, validators=[chirps.models.validate_content]),
        ),
    ]
