# Generated by Django 2.0.3 on 2018-03-20 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0006_auto_20180318_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chirp',
            options={'ordering': ['-timestamp', 'content']},
        ),
    ]
